import './style.css'
import { users } from './data/users.js'
import { roles } from './data/roles.js'
import { providers } from './data/providers.js'
import { products } from './data/products.js'
import { purchases } from './data/purchases.js'
import { sales } from './data/sales.js'
import { invoices } from './data/invoices.js'

const app = document.querySelector('#app')
const money = value => new Intl.NumberFormat('es-GT',{style:'currency',currency:'GTQ'}).format(value)
const icons = {dashboard:'⌂',users:'♙',roles:'♢',providers:'▣',inventory:'□',purchases:'↓',sales:'↑',invoices:'▤'}
const labels = {dashboard:'Dashboard',users:'Usuarios',roles:'Roles',providers:'Proveedores',inventory:'Inventario',purchases:'Compras',sales:'Ventas',invoices:'Facturación'}
let current = 'login', saleRows = [{product:'Monitor',price:1399,qty:1}], purchaseRows = [{product:'Teclado',price:180,qty:5}]

const badge = value => `<span class="badge ${['Activo','Completada','Emitida'].includes(value)?'success':value==='Inactivo'||value==='Anulada'?'danger':'warning'}">${value}</span>`
const actions = (view=true) => `<div class="actions">${view?'<button class="icon-btn" data-action="view" title="Ver">◉</button>':''}<button class="icon-btn" data-action="edit" title="Editar">✎</button><button class="icon-btn danger-text" data-action="disable" title="Desactivar">⊘</button></div>`
const pageHead = (title,subtitle,button='') => `<div class="page-head"><div><p class="eyebrow">ADMINISTRACIÓN</p><h1>${title}</h1><p>${subtitle}</p></div>${button}</div>`
const table = (heads,rows) => `<div class="table-wrap"><table><thead><tr>${heads.map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${rows}</tbody></table></div>`

function login(){
  app.innerHTML=`<main class="login"><section class="login-brand"><div class="brand-mark">N</div><div><span>Nexo</span>Ventas</div><h1>Todo tu negocio,<br>en un solo lugar.</h1><p>Administra ventas, inventario y facturación desde una plataforma simple y eficiente.</p><div class="feature"><b>✓</b><span><strong>Control total en tiempo real</strong><small>Información clara para tomar mejores decisiones.</small></span></div></section><section class="login-panel"><form id="login-form" class="login-card"><div class="mobile-brand"><b>N</b> NexoVentas</div><p class="eyebrow">BIENVENIDO DE NUEVO</p><h2>Iniciar sesión</h2><p>Ingresa tus datos para acceder al sistema.</p><label>Usuario o correo<input required value="admin" placeholder="nombre@empresa.com"></label><label>Contraseña<div class="password"><input required type="password" value="admin123"><button type="button" id="toggle-pass">◉</button></div></label><div class="form-line"><label class="check"><input type="checkbox"> Recordarme</label><a href="#" id="forgot">¿Olvidó su contraseña?</a></div><button class="btn primary full" type="submit">Iniciar sesión <span>→</span></button><small class="demo">Prototipo visual · Puede usar cualquier credencial</small></form></section></main>`
}

function shell(content){
 app.innerHTML=`<div class="layout"><aside id="sidebar"><div class="logo"><b>N</b><span>Nexo<em>Ventas</em></span></div><nav>${Object.entries(labels).map(([k,v])=>`<button data-route="${k}" class="${current===k?'active':''}"><i>${icons[k]}</i>${v}</button>`).join('')}</nav><div class="side-user"><div class="avatar">CP</div><span><strong>Carlos Pérez</strong><small>Administrador</small></span><button data-route="login" title="Cerrar sesión">↪</button></div></aside><div class="main"><header><button id="menu">☰</button><div class="crumb">NexoVentas <span>/</span> ${labels[current]}</div><div class="header-tools"><button class="bell">♢<i></i></button><div class="avatar">CP</div><span><strong>Carlos Pérez</strong><small>Administrador</small></span></div></header><main class="content">${content}</main></div></div><div id="modal-root"></div><div id="toast"></div>`
}

function dashboard(){
 const cards=[['Productos','24','inventory','+3 este mes'],['Poco stock','4','warning','Requieren atención'],['Ventas registradas','18','sales','+12% este mes'],['Compras registradas','11','purchases','+2 esta semana'],['Proveedores','6','providers','Todos verificados'],['Facturas emitidas','18','invoices','100% procesadas']]
 shell(`${pageHead('Dashboard','Resumen general de tu negocio.')}<div class="stats">${cards.map(x=>`<article class="stat"><div class="stat-icon ${x[2]}">${icons[x[2]]||'!'}</div><span>${x[0]}</span><strong>${x[1]}</strong><small>${x[3]}</small></article>`).join('')}</div><div class="grid-2"><section class="card"><div class="card-head"><div><h2>Últimas ventas</h2><p>Transacciones recientes</p></div><button class="link" data-route="sales">Ver todas →</button></div>${table(['Venta','Vendedor','Fecha','Total'],sales.slice(0,3).map(s=>`<tr><td><b>${s.number}</b></td><td>${s.seller}</td><td>${s.date}</td><td><b>${money(s.total)}</b></td></tr>`).join(''))}</section><section class="card"><div class="card-head"><div><h2>Inventario bajo</h2><p>Productos por reabastecer</p></div><button class="link" data-route="inventory">Ver inventario →</button></div>${products.filter(p=>p.stock<=p.min).slice(0,4).map(p=>`<div class="stock-row"><div class="product-icon">${p.name[0]}</div><span><b>${p.name}</b><small>${p.code}</small></span><div><b>${p.stock} unidades</b><small>Mínimo: ${p.min}</small></div><span class="dot ${p.stock?'yellow':'red'}"></span></div>`).join('')}</section></div><section class="card recent"><div class="card-head"><div><h2>Últimas compras</h2><p>Ingresos recientes al inventario</p></div><button class="link" data-route="purchases">Ver historial →</button></div>${table(['Compra','Proveedor','Fecha','Usuario','Total','Estado'],purchases.map(p=>`<tr><td><b>${p.number}</b></td><td>${p.provider}</td><td>${p.date}</td><td>${p.user}</td><td><b>${money(p.total)}</b></td><td>${badge(p.status)}</td></tr>`).join(''))}</section>`)
}

function usersPage(){shell(`${pageHead('Gestión de Usuarios','Administra las cuentas y accesos del personal.','<button class="btn primary" data-modal="user">＋ Nuevo usuario</button>')}${table(['ID','Nombre','Usuario','Correo','Rol','Estado','Acciones'],users.map(u=>`<tr><td>#${String(u.id).padStart(3,'0')}</td><td><b>${u.name}</b></td><td>@${u.username}</td><td>${u.email}</td><td><span class="role">${u.role}</span></td><td>${badge(u.status)}</td><td>${actions()}</td></tr>`).join(''))}`)}
function rolesPage(){shell(`${pageHead('Roles del Sistema','Permisos disponibles para cada tipo de usuario.')}<div class="role-grid">${roles.map((r,i)=>`<article class="role-card"><div class="role-top"><div class="role-icon r${i}">${['♜','↗','▦'][i]}</div><span>${r.permissions.length} permisos</span></div><h2>${r.name}</h2><p>${r.description}</p><hr><h3>Acceso permitido</h3><ul>${r.permissions.map(x=>`<li>✓ <span>${x}</span></li>`).join('')}</ul><button class="btn secondary full" data-action="edit">Configurar rol</button></article>`).join('')}</div>`)}
function providersPage(){shell(`${pageHead('Proveedores','Directorio de socios comerciales.','<button class="btn primary" data-modal="provider">＋ Nuevo proveedor</button>')}<div class="toolbar"><div class="search">⌕ <input placeholder="Buscar proveedor..."></div><select><option>Todos los estados</option><option>Activos</option><option>Inactivos</option></select></div>${table(['ID','Nombre','Empresa','NIT','Teléfono','Correo','Estado','Acciones'],providers.map(p=>`<tr><td>#${String(p.id).padStart(3,'0')}</td><td><b>${p.name}</b></td><td>${p.company}</td><td>${p.nit}</td><td>${p.phone}</td><td>${p.email}</td><td>${badge(p.status)}</td><td>${actions()}</td></tr>`).join(''))}`)}
function stockStatus(p){return p.stock===0?['Sin stock','danger']:p.stock<=p.min?['Poco stock','warning']:['Normal','success']}
function inventoryPage(){shell(`${pageHead('Inventario','Control de productos y existencias.','<button class="btn primary" data-modal="product">＋ Nuevo producto</button>')}<div class="toolbar"><div class="search">⌕ <input id="product-search" placeholder="Buscar por código o producto..."></div><select id="stock-filter"><option value="">Todos los estados</option><option>Normal</option><option>Poco stock</option><option>Sin stock</option></select></div><div id="product-table">${productTable(products)}</div>`)}
function productTable(items){return table(['Código','Producto','Descripción','Precio compra','Precio venta','Existencia','Stock mínimo','Estado','Acciones'],items.map(p=>{const s=stockStatus(p);return `<tr><td><b>${p.code}</b></td><td><b>${p.name}</b></td><td>${p.description}</td><td>${money(p.buy)}</td><td><b>${money(p.sell)}</b></td><td><b>${p.stock}</b></td><td>${p.min}</td><td>${badge(s[0])}</td><td>${actions(false)}</td></tr>`}).join(''))}

function purchasesPage(){const total=purchaseRows.reduce((a,r)=>a+r.price*r.qty,0);shell(`${pageHead('Nueva Compra','Registra el ingreso de productos al inventario.')}<section class="card form-card"><div class="section-title"><b>Información de compra</b><span>Datos generales</span></div><div class="form-grid four"><label>Número de compra<input value="C-0012" disabled></label><label>Fecha<input type="date" value="2026-08-28"></label><label>Proveedor<select><option>Tecno Suministros</option>${providers.slice(1).map(p=>`<option>${p.company}</option>`)}</select></label><label>Usuario que registra<input value="Ana Morales" disabled></label></div></section><section class="card form-card"><div class="section-title line"><div><b>Detalle de Compra</b><span>Productos incluidos</span></div><button class="btn secondary" id="add-purchase">＋ Agregar producto</button></div>${lineTable(purchaseRows,'purchase')}<div class="totals"><span>Subtotal general <b>${money(total)}</b></span><span class="grand">Total <b>${money(total)}</b></span></div></section><div class="footer-actions"><button class="btn secondary" data-action="cancel">Cancelar</button><button class="btn primary" data-register="Compra">✓ Registrar compra</button></div><section class="card history"><div class="card-head"><div><h2>Historial de Compras</h2><p>Movimientos registrados recientemente</p></div></div>${table(['Número compra','Proveedor','Fecha','Total','Usuario','Estado'],purchases.map(p=>`<tr><td><b>${p.number}</b></td><td>${p.provider}</td><td>${p.date}</td><td><b>${money(p.total)}</b></td><td>${p.user}</td><td>${badge(p.status)}</td></tr>`).join(''))}</section>`)}
function salesPage(){const total=saleRows.reduce((a,r)=>a+r.price*r.qty,0);shell(`${pageHead('Nueva Venta','Registra una nueva transacción comercial.')}<section class="card form-card"><div class="section-title"><b>Información de venta</b><span>Datos generales</span></div><div class="form-grid three"><label>Número de venta<input value="V-0019" disabled></label><label>Fecha<input type="date" value="2026-08-28"></label><label>Vendedor<input value="María López" disabled></label></div></section><section class="card form-card"><div class="section-title line"><div><b>Detalle de Venta</b><span>Productos de la transacción</span></div><button class="btn secondary" id="add-sale">＋ Agregar producto</button></div>${lineTable(saleRows,'sale')}<div class="totals"><span>Subtotal <b>${money(total)}</b></span><span class="grand">Total <b>${money(total)}</b></span></div></section><div class="footer-actions"><button class="btn secondary" data-action="cancel">Cancelar</button><button class="btn primary" data-register="Venta">✓ Registrar venta</button></div><section class="card history"><div class="card-head"><div><h2>Historial de Ventas</h2><p>Transacciones registradas</p></div></div>${table(['Número','Fecha','Vendedor','Total','Estado','Acciones'],sales.map(s=>`<tr><td><b>${s.number}</b></td><td>${s.date}</td><td>${s.seller}</td><td><b>${money(s.total)}</b></td><td>${badge(s.status)}</td><td><button class="icon-btn" data-action="view">◉</button></td></tr>`).join(''))}</section>`)}
function lineTable(rows,type){return table(['Producto',type==='purchase'?'Precio compra':'Precio','Cantidad','Subtotal','Acción'],rows.map((r,i)=>`<tr><td><select class="line-product" data-type="${type}" data-index="${i}">${products.map(p=>`<option value="${p.name}" ${p.name===r.product?'selected':''}>${p.name}</option>`)}</select></td><td>${money(r.price)}</td><td><input class="qty" data-type="${type}" data-index="${i}" type="number" min="1" value="${r.qty}"></td><td><b>${money(r.price*r.qty)}</b></td><td><button class="icon-btn danger-text remove-row" data-type="${type}" data-index="${i}">✕</button></td></tr>`).join(''))}

function invoicesPage(){shell(`${pageHead('Facturación','Consulta y administra las facturas emitidas.')}<div class="toolbar"><div class="search">⌕ <input placeholder="Buscar factura o venta..."></div><select><option>Todos los estados</option><option>Emitida</option></select></div>${table(['Número de factura','Número de venta','Fecha','Vendedor','Total','Estado','Acciones'],invoices.map((f,i)=>`<tr><td><b>${f.number}</b></td><td>${f.sale}</td><td>${f.date}</td><td>${f.seller}</td><td><b>${money(f.total)}</b></td><td>${badge(f.status)}</td><td><div class="actions"><button class="btn tiny" data-invoice="${i}">◉ Ver factura</button><button class="icon-btn print-invoice" data-invoice="${i}" title="Imprimir">▣</button></div></td></tr>`).join(''))}`)}
function invoiceDetail(i){const f=invoices[i];shell(`<button class="back" data-route="invoices">← Volver a facturación</button><section class="invoice card"><div class="invoice-head"><div class="logo dark"><b>N</b><span>Nexo<em>Ventas</em></span></div><div><p>FACTURA</p><h1>${f.number}</h1></div></div><div class="invoice-meta"><div><small>FACTURADO POR</small><b>NexoVentas, S.A.</b><span>NIT: 548721-3</span><span>Ciudad de Guatemala</span></div><div><small>DETALLES</small><span>Fecha: <b>${f.date}</b></span><span>Venta: <b>${f.sale}</b></span><span>Vendedor: <b>${f.seller}</b></span></div></div>${table(['Producto','Cantidad','Precio unitario','Subtotal'],`<tr><td><b>Monitor LED 24 pulgadas</b><small class="block">P-003</small></td><td>1</td><td>${money(1399)}</td><td><b>${money(1399)}</b></td></tr><tr><td><b>Teclado mecánico USB</b><small class="block">P-001</small></td><td>1</td><td>${money(250)}</td><td><b>${money(250)}</b></td></tr>`)}<div class="invoice-total"><span>Subtotal <b>${money(f.total)}</b></span><span class="grand">TOTAL <b>${money(f.total)}</b></span></div><div class="invoice-foot"><p>Gracias por su compra.</p><button class="btn primary" id="print">▣ Imprimir factura</button></div></section>`)}

const modalFields={user:[['Nombre','text'],['Apellido','text'],['Usuario','text'],['Correo','email'],['Contraseña','password'],['Rol','select'],['Estado','select']],provider:[['Nombre','text'],['Empresa','text'],['NIT','text'],['Teléfono','tel'],['Correo','email'],['Dirección','text'],['Estado','select']],product:[['Código','text'],['Nombre','text'],['Descripción','text'],['Precio compra','number'],['Precio venta','number'],['Stock','number'],['Stock mínimo','number']]}
function openModal(type){const title={user:'Nuevo usuario',provider:'Nuevo proveedor',product:'Nuevo producto'}[type];document.querySelector('#modal-root').innerHTML=`<div class="modal-back"><div class="modal"><div class="modal-head"><div><h2>${title}</h2><p>Completa la información del formulario.</p></div><button id="close-modal">✕</button></div><form id="modal-form" class="form-grid two">${modalFields[type].map(([n,t])=>`<label>${n}${t==='select'?`<select required><option>${n==='Rol'?'Administrador':'Activo'}</option><option>${n==='Rol'?'Vendedor':'Inactivo'}</option></select>`:`<input type="${t}" required placeholder="Ingresa ${n.toLowerCase()}">`}</label>`).join('')}<div class="modal-actions"><button class="btn secondary" type="button" id="cancel-modal">Cancelar</button><button class="btn primary" type="submit">Guardar (simulación)</button></div></form></div></div>`}
function toast(msg){const el=document.querySelector('#toast');if(!el)return;el.textContent='✓  '+msg;el.className='show';setTimeout(()=>el.className='',3000)}
function render(route){current=route;if(route==='login')return login();({dashboard,users:usersPage,roles:rolesPage,providers:providersPage,inventory:inventoryPage,purchases:purchasesPage,sales:salesPage,invoices:invoicesPage}[route]||dashboard)()}

document.addEventListener('click',e=>{
 const route=e.target.closest('[data-route]')?.dataset.route;if(route){render(route);return}
 if(e.target.closest('#menu'))document.querySelector('#sidebar').classList.toggle('open')
 const modal=e.target.closest('[data-modal]')?.dataset.modal;if(modal)openModal(modal)
 if(e.target.closest('#close-modal')||e.target.closest('#cancel-modal'))document.querySelector('#modal-root').innerHTML=''
 if(e.target.closest('#toggle-pass')){const input=document.querySelector('.password input');input.type=input.type==='password'?'text':'password'}
 if(e.target.closest('#forgot')){e.preventDefault();alert('Recuperación de contraseña — simulación visual.')}
 const reg=e.target.closest('[data-register]')?.dataset.register;if(reg)toast(`${reg} registrada correctamente — simulación de prototipo.`)
 if(e.target.closest('[data-action]'))toast('Acción simulada correctamente.')
 if(e.target.closest('#add-sale')){saleRows.push({product:'Mouse',price:120,qty:1});salesPage()}
 if(e.target.closest('#add-purchase')){purchaseRows.push({product:'Mouse',price:75,qty:1});purchasesPage()}
 const remove=e.target.closest('.remove-row');if(remove){const list=remove.dataset.type==='sale'?saleRows:purchaseRows;list.splice(+remove.dataset.index,1);remove.dataset.type==='sale'?salesPage():purchasesPage()}
 const inv=e.target.closest('[data-invoice]');if(inv){if(inv.classList.contains('print-invoice'))window.print();else invoiceDetail(+inv.dataset.invoice)}
 if(e.target.closest('#print'))window.print()
})
document.addEventListener('submit',e=>{e.preventDefault();if(e.target.id==='login-form')render('dashboard');if(e.target.id==='modal-form'){document.querySelector('#modal-root').innerHTML='';toast('Datos guardados únicamente en la simulación.')}})
document.addEventListener('input',e=>{
 if(e.target.matches('.qty')){const list=e.target.dataset.type==='sale'?saleRows:purchaseRows;list[+e.target.dataset.index].qty=Math.max(1,+e.target.value);e.target.dataset.type==='sale'?salesPage():purchasesPage()}
 if(e.target.id==='product-search'||e.target.id==='stock-filter'){const q=(document.querySelector('#product-search')?.value||'').toLowerCase(),f=document.querySelector('#stock-filter')?.value;document.querySelector('#product-table').innerHTML=productTable(products.filter(p=>(p.name.toLowerCase().includes(q)||p.code.toLowerCase().includes(q))&&(!f||stockStatus(p)[0]===f)))}
})
document.addEventListener('change',e=>{if(e.target.matches('.line-product')){const p=products.find(x=>x.name===e.target.value),list=e.target.dataset.type==='sale'?saleRows:purchaseRows;list[+e.target.dataset.index]={product:p.name,price:e.target.dataset.type==='sale'?p.sell:p.buy,qty:list[+e.target.dataset.index].qty};e.target.dataset.type==='sale'?salesPage():purchasesPage()}})
render('login')
